[Server]
servername = MojoBolSampleServer
serverdir = /opt/voiceofhimalaya
playertype= asterisk
tts = espeak
language = en
workflowpath = /opt/voh
loglevel = debug
logfile = logs/mojobolsample.log
callsdir = calls/
reportsdir = reports/
callkey = call_id
tsformat = %Y-%b-%d-%H-%M-%S
